In [4]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from factor_analyzer import FactorAnalyzer
from statsmodels.stats.outliers_influence import variance_inflation_factor
from statsmodels.tools.tools import add_constant
from sklearn.decomposition import PCA

plt.rc('font', family='Malgun Gothic')
sns.set(font="Malgun Gothic",#"NanumGothicCoding", 
        rc={"axes.unicode_minus":False}, # 마이너스 부호 깨짐 현상 해결
        style='darkgrid')


In [2]:
data=pd.read_csv("C:/Users/guswn/OneDrive/바탕 화면/생활인구/lp_df4.csv",encoding="cp949")

In [13]:
data

행정구역  2023년06월_거주자 인구수  전입인구(2022.1~2023.5)  전출인구(2022.1~2023.5)  \
0   태백시             38802                 5139                 6335   
1   삼척시             63115                11049                10431   
2   홍천군             67448                 9440                 9327   
3   횡성군             46439                 6365                 5504   
4   영월군             37425                 4912                 4568   
..  ...               ...                  ...                  ...   
66  하동군             41959                 4851                 5237   
67  산청군             34025                 4638                 4010   
68  함양군             37172                 4227                 4338   
69  거창군             60198                 6920                 6720   
70  합천군             41455                 4697                 4669   

       22생활인구평균  클러스터  인구수_대비_생활인구  관광 활성화 지수  
0   2555405.325     4    65.857567       16.6  
1   3565265.747     4    56.488406       42.2  
2   4075700.482     4    60.427299       62.3  
3   2649233.625     4    57.047603       32.9  
4   1861082.523     4    49.728324       29.3  
..          ...   ...          ...        ...  
66  1787245.254     4    42.595039       21.2  
67  1685688.525     4    49.542646       29.4  
68  2047514.484     4    55.082172       18.3  
69  2706173.278     4    44.954538       20.0  
70  2091035.929     4    50.441103       18.2  

[71 rows x 8 columns]

In [14]:
data=data.drop("클러스터",axis=1)

In [20]:
#PCA 의미가 없음 
pca = PCA(n_components=2) #분산설명량 체크하면서 바꿈
# 데이터를 PCA 모델에 적합 (주성분 찾기)
pca.fit(data.iloc[:,1:])

# 데이터를 주성분으로 변환
transformed_data = pca.transform(data.iloc[:,1:])

# 설명가능한 분산량 (explained variance) 출력
explained_variance = pca.explained_variance_ratio_
print("설명가능한 분산량:", explained_variance)

설명가능한 분산량: [9.99916968e-01 7.87536709e-05]


In [17]:
transformed_data

array([[  321171.30847757],
       [ 1331291.89849363],
       [ 1841729.40430072],
       [  415100.03543999],
       [ -373100.93246221],
       [ 1024094.52390564],
       [  182370.98387052],
       [  542219.71640505],
       [ -514536.95727941],
       [ -839162.34236708],
       [   69218.28604023],
       [  234677.83754251],
       [  606207.95248788],
       [ -400647.17718195],
       [  819152.36790817],
       [  404009.74623132],
       [ -267548.27667815],
       [ -174684.84399695],
       [ -488049.64960353],
       [ -245051.64270102],
       [ 1049404.68597247],
       [ 1729872.80750135],
       [  737101.03826737],
       [ -450155.07527061],
       [ 2493171.96587002],
       [-1235235.37373081],
       [ -924528.04272969],
       [-1280434.33179906],
       [-1135109.1235558 ],
       [-1129714.1972558 ],
       [  388551.48156248],
       [  522495.73188714],
       [  235024.00941241],
       [ -869396.97979054],
       [ -998659.39588548],
       [  240679.495

In [21]:
factor_analyzer = FactorAnalyzer(n_factors=5, rotation=None)  # 25는 예상되는 요인의 수입니다. 적절한 수를 선택하여 수정
factor_analyzer.fit(transformed_data)



FactorAnalyzer(n_factors=5, rotation=None, rotation_kwargs={})

In [22]:
factor_analyzer.loadings_

array([[3.88190796e-07, 0.00000000e+00],
       [3.88190796e-07, 0.00000000e+00]])

In [24]:
#PCA 가 필요없음
factor_analyzer = FactorAnalyzer(n_factors=3, rotation=None)  # 25는 예상되는 요인의 수입니다. 적절한 수를 선택하여 수정
factor_analyzer.fit(data.iloc[:,1:])

FactorAnalyzer(rotation=None, rotation_kwargs={})

In [26]:
print(factor_analyzer.loadings_)

[[ 0.92826645 -0.21590329 -0.29528919]
 [ 0.91486063 -0.24103505  0.31819063]
 [ 0.92730678 -0.21818431  0.21168944]
 [ 0.91467399  0.31016101 -0.24883448]
 [ 0.08723572  0.94344857  0.14172401]
 [ 0.43885309  0.58619711  0.00443187]]


In [36]:
factor_analyzer.loadings_[abs(factor_analyzer.loadings_)<0.3]=0

In [37]:
factor_analyzer.loadings_

array([[0.92826645, 0.        , 0.        ],
       [0.91486063, 0.        , 0.31819063],
       [0.92730678, 0.        , 0.        ],
       [0.91467399, 0.31016101, 0.        ],
       [0.        , 0.94344857, 0.        ],
       [0.43885309, 0.58619711, 0.        ]])